# Generated by Django 4.2.7 on 2025-12-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('father_name', models.CharField(blank=True, max_length=255, verbose_name='نام پدر')),
                ('current_address', models.TextField(blank=True, verbose_name='نشانی فعلی')),
                ('permanent_address', models.TextField(blank=True, verbose_name='نشانی دایمی')),
                ('mobile_number', models.CharField(blank=True, max_length=20, verbose_name='شماره موبایل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='عکس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
            ],
            options={
                'verbose_name': 'دانش\u200cآموز',
                'verbose_name_plural': 'دانش\u200cآموزان',
            },
        ),
    ]
