# Generated by Django 4.2.7 on 2025-12-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام و تخلص استاد')),
                ('father_name', models.CharField(blank=True, max_length=255, verbose_name='نام پدر')),
                ('permanent_address', models.TextField(blank=True, verbose_name='سکونت اصلی')),
                ('current_address', models.TextField(blank=True, verbose_name='سکونت فعلی')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], default='male', max_length=10, verbose_name='جنسیت')),
                ('education_level', models.CharField(choices=[('p', 'پاس'), ('b', 'لیسانس'), ('m', 'ماستر'), ('d', 'دوکتور')], default='p', max_length=2, verbose_name='سویه تحصیلی')),
                ('id_number', models.CharField(blank=True, max_length=100, verbose_name='نمبر تذکره')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, verbose_name='سمستر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('classes', models.ManyToManyField(blank=True, to='core.schoolclass', verbose_name='صنوف')),
                ('subjects', models.ManyToManyField(blank=True, to='core.subject', verbose_name='مضامین')),
            ],
            options={
                'verbose_name': 'استاد',
                'verbose_name_plural': 'اساتید',
            },
        ),
    ]
