# Generated by Django 4.2.7 on 2025-12-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='شماره سمستر')),
            ],
            options={
                'verbose_name': 'سمستر',
                'verbose_name_plural': 'سمسترها',
            },
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='semester',
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='عکس'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='semesters',
            field=models.ManyToManyField(blank=True, to='core.semester', verbose_name='سمسترها'),
        ),
    ]
