# Generated by Django 4.2.7 on 2025-12-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_semester_remove_teacher_semester_teacher_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='education_level',
            field=models.CharField(choices=[('p', 'چهارده پاس'), ('b', 'لیسانس'), ('m', 'ماستر'), ('d', 'دوکتور')], default='p', max_length=2, verbose_name='سویه تحصیلی'),
        ),
    ]
