# Generated by Django 4.2.7 on 2025-12-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_teacher_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان سکونت فعلی تا'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان سکونت فعلی از'),
        ),
        migrations.AddField(
            model_name='student',
            name='exam_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='نمبر امتحان کانکور'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'مذکر'), ('female', 'مونث')], default='male', max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='student',
            name='grandfather_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام پدر کلان'),
        ),
        migrations.AddField(
            model_name='student',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='نمبر تذکره'),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان سکونت دایمی تا'),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان سکونت دایمی از'),
        ),
    ]
