# Generated by Django 4.2.7 on 2025-12-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_student_current_time_end_student_current_time_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_time_end',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_time_start',
        ),
        migrations.RemoveField(
            model_name='student',
            name='permanent_time_end',
        ),
        migrations.RemoveField(
            model_name='student',
            name='permanent_time_start',
        ),
        migrations.AddField(
            model_name='student',
            name='time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='تایم ختم'),
        ),
        migrations.AddField(
            model_name='student',
            name='time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='تایم آغاز'),
        ),
    ]
