# Generated by Codex on 2026-02-05

from django.db import migrations


def _column_exists(schema_editor, table, column):
    vendor = schema_editor.connection.vendor
    cursor = schema_editor.connection.cursor()
    if vendor == 'sqlite':
        cursor.execute(f"PRAGMA table_info('{table}')")
        return column in [row[1] for row in cursor.fetchall()]
    try:
        desc = schema_editor.connection.introspection.get_table_description(cursor, table)
        return column in [c.name for c in desc]
    except Exception:
        return False


def add_schoolclass_period_column(apps, schema_editor):
    if _column_exists(schema_editor, 'core_schoolclass', 'period_id'):
        return
    schema_editor.execute('ALTER TABLE "core_schoolclass" ADD COLUMN "period_id" bigint NULL')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_schoolclass_level'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_schoolclass_period_column, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[],
        ),
    ]
