# Generated by Codex on 2026-02-05

from django.db import migrations, models
import django.db.models.deletion


def create_teacher_contract_table_if_missing(apps, schema_editor):
    existing = schema_editor.connection.introspection.table_names()
    if 'core_teachercontract' in existing:
        return

    vendor = schema_editor.connection.vendor

    if vendor == 'sqlite':
        schema_editor.execute(
            'CREATE TABLE IF NOT EXISTS "core_teachercontract" ('
            '"id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, '
            '"teacher_id" bigint NOT NULL UNIQUE, '
            '"contract_number" varchar(100) NULL, '
            '"contract_date" date NULL, '
            '"start_date" date NULL, '
            '"end_date" date NULL, '
            '"monthly_salary" varchar(100) NULL, '
            '"position" varchar(150) NULL, '
            '"work_hours" varchar(150) NULL, '
            '"terms" text NULL, '
            '"signed_file" varchar(255) NULL, '
            '"created_at" datetime NOT NULL, '
            '"updated_at" datetime NOT NULL'
            ')'
        )
        schema_editor.execute(
            'CREATE INDEX IF NOT EXISTS "core_teachercontract_teacher_id" '
            'ON "core_teachercontract" ("teacher_id")'
        )
        return

    if vendor == 'postgresql':
        schema_editor.execute(
            'CREATE TABLE IF NOT EXISTS "core_teachercontract" ('
            '"id" bigserial PRIMARY KEY, '
            '"teacher_id" bigint NOT NULL UNIQUE, '
            '"contract_number" varchar(100) NULL, '
            '"contract_date" date NULL, '
            '"start_date" date NULL, '
            '"end_date" date NULL, '
            '"monthly_salary" varchar(100) NULL, '
            '"position" varchar(150) NULL, '
            '"work_hours" varchar(150) NULL, '
            '"terms" text NULL, '
            '"signed_file" varchar(255) NULL, '
            '"created_at" timestamp with time zone NOT NULL, '
            '"updated_at" timestamp with time zone NOT NULL'
            ')'
        )
        schema_editor.execute(
            'CREATE INDEX IF NOT EXISTS "core_teachercontract_teacher_id" '
            'ON "core_teachercontract" ("teacher_id")'
        )
        return

    if vendor == 'mysql':
        schema_editor.execute(
            'CREATE TABLE IF NOT EXISTS `core_teachercontract` ('
            '`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, '
            '`teacher_id` bigint NOT NULL UNIQUE, '
            '`contract_number` varchar(100) NULL, '
            '`contract_date` date NULL, '
            '`start_date` date NULL, '
            '`end_date` date NULL, '
            '`monthly_salary` varchar(100) NULL, '
            '`position` varchar(150) NULL, '
            '`work_hours` varchar(150) NULL, '
            '`terms` longtext NULL, '
            '`signed_file` varchar(255) NULL, '
            '`created_at` datetime(6) NOT NULL, '
            '`updated_at` datetime(6) NOT NULL'
            ')'
        )
        schema_editor.execute(
            'CREATE INDEX `core_teachercontract_teacher_id` '
            'ON `core_teachercontract` (`teacher_id`)'
        )
        return

    schema_editor.execute(
        'CREATE TABLE IF NOT EXISTS "core_teachercontract" ('
        '"id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, '
        '"teacher_id" bigint NOT NULL UNIQUE, '
        '"contract_number" varchar(100) NULL, '
        '"contract_date" date NULL, '
        '"start_date" date NULL, '
        '"end_date" date NULL, '
        '"monthly_salary" varchar(100) NULL, '
        '"position" varchar(150) NULL, '
        '"work_hours" varchar(150) NULL, '
        '"terms" text NULL, '
        '"signed_file" varchar(255) NULL, '
        '"created_at" datetime NOT NULL, '
        '"updated_at" datetime NOT NULL'
        ')'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_subject_level_period'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_teacher_contract_table_if_missing, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='TeacherContract',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='شماره قرارداد')),
                        ('contract_date', models.DateField(blank=True, null=True, verbose_name='تاریخ قرارداد')),
                        ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                        ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ختم')),
                        ('monthly_salary', models.CharField(blank=True, max_length=100, verbose_name='معاش ماهوار')),
                        ('position', models.CharField(blank=True, max_length=150, verbose_name='وظیفه/سمت')),
                        ('work_hours', models.CharField(blank=True, max_length=150, verbose_name='ساعات کاری')),
                        ('terms', models.TextField(blank=True, verbose_name='شرایط و توضیحات')),
                        ('signed_file', models.FileField(blank=True, null=True, upload_to='teacher_contracts/signed/', verbose_name='قرارداد امضاشده')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در')),
                        ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='core.teacher', verbose_name='استاد')),
                    ],
                    options={
                        'verbose_name': 'قرارداد استاد',
                        'verbose_name_plural': 'قراردادهای اساتید',
                    },
                ),
            ],
        ),
    ]

